[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -p no:anyio
filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning
    ignore::FutureWarning
norecursedirs = .git data models outputs .pytest_cache
