"""
Comprehensive ML Validation & Robustness Evaluation Suite.
Problem Statement ID: 26064

Executes:
1. Multi-Seed Evaluation (Seeds 1, 10, 42, 100, 999)
2. Noise Robustness Sweep (Low, Medium, High, Very High)
3. Anomaly-Strength Analysis (Very Weak, Weak, Medium, Strong, Very Strong)
4. Threshold Sensitivity Sweep (tau: 0.30 to 0.80)
5. Cross-Condition Testing & Failure-Case Mapping
6. Real Data Schema & Immutability Validation

NOTE: All results generated by this suite are SYNTHETIC DEVELOPMENT RESULTS.
They validate ML pipeline stability, but do NOT represent real seafloor sensor performance.
"""

import json
import os
import sys
import time
from typing import Any, Dict, List, Tuple

sys.path.insert(0, os.path.abspath("."))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score

from src.config import load_config
from src.data_generator import SyntheticDataGenerator
from src.pipeline import SeafloorAnomalyPipeline


def run_experiment(
    cfg_override: Dict[str, Any],
    num_samples: int = 2500,
    seed: int = 42,
    threshold: float = 0.65,
) -> Dict[str, Any]:
    """Runs a single controlled synthetic experiment and returns metrics and score distributions."""
    cfg = load_config()
    
    # Apply overrides
    for k, v in cfg_override.items():
        if isinstance(v, dict) and k in cfg:
            cfg[k].update(v)
        else:
            cfg[k] = v
            
    cfg["synthetic_generator"]["num_samples"] = num_samples
    cfg["synthetic_generator"]["random_seed"] = seed
    
    generator = SyntheticDataGenerator(cfg)
    df_data = generator.generate(return_ground_truth=True)
    
    pipeline = SeafloorAnomalyPipeline(cfg)
    pipeline.train(df_data)
    
    predictions = pipeline.predict(df_data, threshold=threshold)
    scores = np.array([p["anomaly_score"] for p in predictions])
    pred_labels = np.array([1 if p["classification"] == "high_anomaly" else 0 for p in predictions])
    
    gt_types = df_data["ground_truth_label"].values
    true_binary = np.array([1 if g == "high_anomaly" else 0 for g in gt_types])
    
    prec = float(precision_score(true_binary, pred_labels, zero_division=0))
    rec = float(recall_score(true_binary, pred_labels, zero_division=0))
    f1 = float(f1_score(true_binary, pred_labels, zero_division=0))
    
    cm = confusion_matrix(true_binary, pred_labels, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    fpr = float(fp / (fp + tn)) if (fp + tn) > 0 else 0.0
    fnr = float(fn / (fn + tp)) if (fn + tp) > 0 else 0.0
    
    # Score distribution by category
    bg_scores = scores[gt_types == "background"]
    low_scores = scores[gt_types == "low_anomaly"]
    high_scores = scores[gt_types == "high_anomaly"]
    
    return {
        "metrics": {
            "precision": round(prec, 4),
            "recall": round(rec, 4),
            "f1_score": round(f1, 4),
            "false_positive_rate": round(fpr, 4),
            "false_negative_rate": round(fnr, 4),
            "tp": int(tp),
            "fp": int(fp),
            "tn": int(tn),
            "fn": int(fn),
        },
        "score_stats": {
            "background_mean": float(np.mean(bg_scores)) if len(bg_scores) > 0 else 0.0,
            "background_median": float(np.median(bg_scores)) if len(bg_scores) > 0 else 0.0,
            "background_p95": float(np.percentile(bg_scores, 95)) if len(bg_scores) > 0 else 0.0,
            "low_mean": float(np.mean(low_scores)) if len(low_scores) > 0 else 0.0,
            "low_median": float(np.median(low_scores)) if len(low_scores) > 0 else 0.0,
            "high_mean": float(np.mean(high_scores)) if len(high_scores) > 0 else 0.0,
            "high_median": float(np.median(high_scores)) if len(high_scores) > 0 else 0.0,
            "high_min": float(np.min(high_scores)) if len(high_scores) > 0 else 0.0,
            "high_max": float(np.max(high_scores)) if len(high_scores) > 0 else 0.0,
        },
        "scores": scores,
        "true_binary": true_binary,
        "gt_types": gt_types,
    }


def multi_seed_evaluation(seeds: List[int] = [1, 10, 42, 100, 999]) -> Dict[str, Any]:
    """Runs deterministic experiments over multiple random seeds."""
    print("Running Multi-Seed Evaluation...")
    results = []
    
    for s in seeds:
        res = run_experiment({}, num_samples=2500, seed=s, threshold=0.65)
        m = res["metrics"]
        results.append({
            "seed": s,
            "precision": m["precision"],
            "recall": m["recall"],
            "f1_score": m["f1_score"],
            "fpr": m["false_positive_rate"],
            "fnr": m["false_negative_rate"],
            "tp": m["tp"],
            "fp": m["fp"],
            "tn": m["tn"],
            "fn": m["fn"],
        })
        
    df_seeds = pd.DataFrame(results)
    
    stats = {}
    for col in ["precision", "recall", "f1_score", "fpr", "fnr"]:
        vals = df_seeds[col].values
        stats[col] = {
            "mean": round(float(np.mean(vals)), 4),
            "std": round(float(np.std(vals)), 4),
            "min": round(float(np.min(vals)), 4),
            "max": round(float(np.max(vals)), 4),
        }
        
    return {
        "individual_runs": results,
        "aggregated_stats": stats,
    }


def noise_robustness_evaluation() -> Dict[str, Any]:
    """Tests ML pipeline across increasing synthetic noise conditions."""
    print("Running Noise Robustness Evaluation...")
    noise_levels = {
        "Low Noise (0.005)": 0.005,
        "Medium Noise (0.015)": 0.015,
        "High Noise (0.035)": 0.035,
        "Very High Noise (0.060)": 0.060,
    }
    
    results = {}
    seeds = [1, 10, 42, 100, 999]
    
    for name, noise_val in noise_levels.items():
        seed_runs = []
        for s in seeds:
            res = run_experiment(
                {"synthetic_generator": {"sensor_noise_std": noise_val}},
                num_samples=2500,
                seed=s,
                threshold=0.65,
            )
            seed_runs.append(res["metrics"])
            
        # Compute mean across seeds for this noise level
        df_noise = pd.DataFrame(seed_runs)
        results[name] = {
            "noise_std": noise_val,
            "precision_mean": round(float(df_noise["precision"].mean()), 4),
            "recall_mean": round(float(df_noise["recall"].mean()), 4),
            "f1_mean": round(float(df_noise["f1_score"].mean()), 4),
            "fpr_mean": round(float(df_noise["false_positive_rate"].mean()), 4),
            "fnr_mean": round(float(df_noise["false_negative_rate"].mean()), 4),
        }
        
    return results


def anomaly_strength_evaluation() -> Dict[str, Any]:
    """Tests score behavior against different synthetic anomaly body strengths."""
    print("Running Anomaly Strength Evaluation...")
    strength_levels = {
        "Very Weak (0.05-0.15)": {"min": 0.05, "max": 0.15},
        "Weak (0.15-0.30)": {"min": 0.15, "max": 0.30},
        "Medium (0.30-0.60)": {"min": 0.30, "max": 0.60},
        "Strong (0.60-1.00)": {"min": 0.60, "max": 1.00},
        "Very Strong (1.00-2.00)": {"min": 1.00, "max": 2.00},
    }
    
    results = {}
    for name, s_cfg in strength_levels.items():
        seed_runs = []
        scores_agg = []
        for s in [1, 10, 42]:
            res = run_experiment(
                {
                    "synthetic_generator": {
                        "high_anomaly_strength_min": s_cfg["min"],
                        "high_anomaly_strength_max": s_cfg["max"],
                    }
                },
                num_samples=2500,
                seed=s,
                threshold=0.65,
            )
            seed_runs.append(res["metrics"])
            scores_agg.append(res["score_stats"])
            
        df_m = pd.DataFrame(seed_runs)
        df_s = pd.DataFrame(scores_agg)
        
        results[name] = {
            "strength_range": [s_cfg["min"], s_cfg["max"]],
            "high_anomaly_mean_score": round(float(df_s["high_mean"].mean()), 4),
            "high_anomaly_median_score": round(float(df_s["high_median"].mean()), 4),
            "background_mean_score": round(float(df_s["background_mean"].mean()), 4),
            "detection_rate (Recall)": round(float(df_m["recall"].mean()), 4),
            "precision": round(float(df_m["precision"].mean()), 4),
            "f1_score": round(float(df_m["f1_score"].mean()), 4),
            "fpr": round(float(df_m["false_positive_rate"].mean()), 4),
        }
        
    return results


def threshold_sensitivity_evaluation() -> Dict[str, Any]:
    """Evaluates metrics across thresholds tau from 0.30 to 0.80."""
    print("Running Threshold Sensitivity Evaluation...")
    thresholds = [0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80]
    
    results = {}
    seeds = [1, 10, 42, 100, 999]
    
    for tau in thresholds:
        seed_runs = []
        for s in seeds:
            res = run_experiment({}, num_samples=2500, seed=s, threshold=tau)
            seed_runs.append(res["metrics"])
            
        df_tau = pd.DataFrame(seed_runs)
        results[f"{tau:.2f}"] = {
            "threshold": tau,
            "precision": round(float(df_tau["precision"].mean()), 4),
            "recall": round(float(df_tau["recall"].mean()), 4),
            "f1_score": round(float(df_tau["f1_score"].mean()), 4),
            "fpr": round(float(df_tau["false_positive_rate"].mean()), 4),
            "fnr": round(float(df_tau["false_negative_rate"].mean()), 4),
            "tp": round(float(df_tau["tp"].mean()), 1),
            "fp": round(float(df_tau["fp"].mean()), 1),
            "tn": round(float(df_tau["tn"].mean()), 1),
            "fn": round(float(df_tau["fn"].mean()), 1),
        }
        
    # Analyze optimal thresholds
    tau_keys = list(results.keys())
    best_f1_key = max(tau_keys, key=lambda k: results[k]["f1_score"])
    best_recall_key = max(tau_keys, key=lambda k: results[k]["recall"])
    min_fpr_key = min(tau_keys, key=lambda k: results[k]["fpr"])
    
    return {
        "threshold_table": results,
        "analysis": {
            "best_f1_threshold": results[best_f1_key]["threshold"],
            "best_f1_value": results[best_f1_key]["f1_score"],
            "max_recall_threshold": results[best_recall_key]["threshold"],
            "max_recall_value": results[best_recall_key]["recall"],
            "min_fpr_threshold": results[min_fpr_key]["threshold"],
            "min_fpr_value": results[min_fpr_key]["fpr"],
            "baseline_threshold_0_65_f1": results["0.65"]["f1_score"],
        },
    }


def cross_condition_evaluation() -> Dict[str, Any]:
    """Identifies failure cases across combinations of noise and anomaly strength."""
    print("Running Cross-Condition Failure-Case Evaluation...")
    noise_levels = [0.005, 0.015, 0.035, 0.060]
    strengths = [
        ("Very Weak", 0.05, 0.15),
        ("Weak", 0.15, 0.30),
        ("Medium", 0.30, 0.60),
        ("Strong", 0.60, 1.20),
    ]
    
    matrix_results = []
    
    for n in noise_levels:
        for s_label, s_min, s_max in strengths:
            seed_metrics = []
            for s in [1, 42, 100]:
                res = run_experiment(
                    {
                        "synthetic_generator": {
                            "sensor_noise_std": n,
                            "high_anomaly_strength_min": s_min,
                            "high_anomaly_strength_max": s_max,
                        }
                    },
                    num_samples=2500,
                    seed=s,
                    threshold=0.65,
                )
                seed_metrics.append(res["metrics"])
                
            df_m = pd.DataFrame(seed_metrics)
            mean_rec = round(float(df_m["recall"].mean()), 4)
            mean_prec = round(float(df_m["precision"].mean()), 4)
            mean_f1 = round(float(df_m["f1_score"].mean()), 4)
            mean_fpr = round(float(df_m["false_positive_rate"].mean()), 4)
            mean_fnr = round(float(df_m["false_negative_rate"].mean()), 4)
            
            status = "STABLE"
            if mean_fnr > 0.30:
                status = "HIGH_FALSE_NEGATIVES (Weak Anomaly Submerged by Noise)"
            elif mean_fpr > 0.05:
                status = "ELEVATED_FALSE_POSITIVES (Noise Triggering High Anomaly)"
                
            matrix_results.append({
                "noise_std": n,
                "anomaly_strength": s_label,
                "strength_range": f"{s_min}-{s_max}",
                "recall": mean_rec,
                "precision": mean_prec,
                "f1_score": mean_f1,
                "fpr": mean_fpr,
                "fnr": mean_fnr,
                "operational_status": status,
            })
            
    return {"matrix": matrix_results}


def generate_validation_plots(
    multi_seed_data: Dict[str, Any],
    noise_data: Dict[str, Any],
    strength_data: Dict[str, Any],
    threshold_data: Dict[str, Any],
    output_dir: str = "outputs/reports",
) -> str:
    """Renders comprehensive validation visualization artifact."""
    os.makedirs(output_dir, exist_ok=True)
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    
    # Plot 1: Multi-Seed Boxplot/Bar
    ax1 = axes[0, 0]
    seeds = [r["seed"] for r in multi_seed_data["individual_runs"]]
    f1s = [r["f1_score"] for r in multi_seed_data["individual_runs"]]
    precs = [r["precision"] for r in multi_seed_data["individual_runs"]]
    recs = [r["recall"] for r in multi_seed_data["individual_runs"]]
    
    x = np.arange(len(seeds))
    w = 0.25
    ax1.bar(x - w, precs, width=w, label="Precision", color="#2b5c8f")
    ax1.bar(x, recs, width=w, label="Recall", color="#3b9a65")
    ax1.bar(x + w, f1s, width=w, label="F1-Score", color="#c27d38")
    ax1.set_xticks(x)
    ax1.set_xticklabels([f"Seed {s}" for s in seeds])
    ax1.set_ylim(0.7, 1.02)
    ax1.set_title("Multi-Seed Performance Consistency (Synthetic)")
    ax1.set_ylabel("Score")
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Plot 2: Noise Robustness Curve
    ax2 = axes[0, 1]
    noise_labels = list(noise_data.keys())
    noise_vals = [noise_data[k]["noise_std"] for k in noise_labels]
    n_f1 = [noise_data[k]["f1_mean"] for k in noise_labels]
    n_rec = [noise_data[k]["recall_mean"] for k in noise_labels]
    n_prec = [noise_data[k]["precision_mean"] for k in noise_labels]
    n_fpr = [noise_data[k]["fpr_mean"] for k in noise_labels]
    
    ax2.plot(noise_vals, n_f1, marker="o", label="F1-Score", color="#c27d38", linewidth=2)
    ax2.plot(noise_vals, n_rec, marker="s", label="Recall", color="#3b9a65", linewidth=2)
    ax2.plot(noise_vals, n_prec, marker="^", label="Precision", color="#2b5c8f", linewidth=2)
    ax2.plot(noise_vals, n_fpr, marker="x", label="FPR", color="#b83838", linestyle="--", linewidth=1.5)
    ax2.set_title("Robustness vs. Sensor Noise Level")
    ax2.set_xlabel("Sensor Noise Std (sigma)")
    ax2.set_ylabel("Metric Value")
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # Plot 3: Anomaly Strength vs Normalized Anomaly Score
    ax3 = axes[1, 0]
    s_labels = list(strength_data.keys())
    s_means = [strength_data[k]["high_anomaly_mean_score"] for k in s_labels]
    s_recs = [strength_data[k]["detection_rate (Recall)"] for k in s_labels]
    s_bg = [strength_data[k]["background_mean_score"] for k in s_labels]
    
    x3 = np.arange(len(s_labels))
    ax3.plot(x3, s_means, marker="o", color="#8f3b76", label="Mean High Anomaly Score", linewidth=2)
    ax3.plot(x3, s_bg, marker="o", color="#3b9a65", label="Mean Background Score", linestyle=":", linewidth=2)
    ax3.plot(x3, s_recs, marker="s", color="#c27d38", label="Detection Rate (Recall)", linewidth=2)
    ax3.axhline(0.65, color="red", linestyle="--", label="Threshold (tau=0.65)")
    ax3.set_xticks(x3)
    ax3.set_xticklabels([k.split()[0] for k in s_labels], rotation=15)
    ax3.set_title("Anomaly Score & Detection Rate vs. Injected Strength")
    ax3.set_ylabel("Score / Rate")
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # Plot 4: Threshold Sensitivity Curve (Precision vs Recall vs F1)
    ax4 = axes[1, 1]
    t_table = threshold_data["threshold_table"]
    taus = [t_table[k]["threshold"] for k in t_table]
    t_f1 = [t_table[k]["f1_score"] for k in t_table]
    t_prec = [t_table[k]["precision"] for k in t_table]
    t_rec = [t_table[k]["recall"] for k in t_table]
    t_fpr = [t_table[k]["fpr"] for k in t_table]
    
    ax4.plot(taus, t_prec, marker="o", label="Precision", color="#2b5c8f", linewidth=2)
    ax4.plot(taus, t_rec, marker="s", label="Recall", color="#3b9a65", linewidth=2)
    ax4.plot(taus, t_f1, marker="^", label="F1-Score", color="#c27d38", linewidth=2)
    ax4.plot(taus, t_fpr, marker="x", label="FPR", color="#b83838", linestyle="--", linewidth=1.5)
    ax4.axvline(0.65, color="black", linestyle=":", label="Baseline (tau=0.65)")
    ax4.set_title("Threshold Sensitivity Trade-Off Curve")
    ax4.set_xlabel("Decision Threshold (tau)")
    ax4.set_ylabel("Metric Value")
    ax4.legend()
    ax4.grid(True, alpha=0.3)
    
    plt.tight_layout()
    chart_path = os.path.join(output_dir, "validation_experimental_summary.png")
    plt.savefig(chart_path, dpi=200)
    plt.close(fig)
    return chart_path


def run_full_validation_suite() -> Dict[str, Any]:
    """Orchestrates all experimental evaluations and exports consolidated report."""
    print("=" * 70)
    print("STARTING FULL ML VALIDATION SUITE (STEP 3)")
    print("=" * 70)
    
    t0 = time.time()
    
    # 1. Multi-Seed
    ms_res = multi_seed_evaluation([1, 10, 42, 100, 999])
    
    # 2. Noise Robustness
    noise_res = noise_robustness_evaluation()
    
    # 3. Anomaly Strength
    strength_res = anomaly_strength_evaluation()
    
    # 4. Threshold Sensitivity
    thresh_res = threshold_sensitivity_evaluation()
    
    # 5. Cross-Condition
    cross_res = cross_condition_evaluation()
    
    # Generate charts
    report_dir = "outputs/reports"
    chart_file = generate_validation_plots(ms_res, noise_res, strength_res, thresh_res, report_dir)
    
    elapsed = round(time.time() - t0, 2)
    
    summary = {
        "suite_metadata": {
            "problem_id": "26064",
            "evaluation_type": "SYNTHETIC DEVELOPMENT EVALUATION",
            "execution_time_seconds": elapsed,
            "disclaimer": "All findings represent synthetic development benchmarking. Re-calibration on ocean sensor data is mandatory.",
        },
        "multi_seed_evaluation": ms_res,
        "noise_robustness": noise_res,
        "anomaly_strength_analysis": strength_res,
        "threshold_sensitivity": thresh_res,
        "cross_condition_failure_cases": cross_res,
        "artifacts_generated": [
            os.path.abspath(chart_file),
            os.path.abspath(os.path.join(report_dir, "validation_results_full.json")),
        ],
    }
    
    out_json = os.path.join(report_dir, "validation_results_full.json")
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
        
    print(f"Validation suite complete in {elapsed}s. Saved results to {out_json} and chart to {chart_file}")
    return summary


if __name__ == "__main__":
    run_full_validation_suite()
